/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as basicVerifierTestSol from "./BasicVerifier.test.sol";
export type { basicVerifierTestSol };
export type { DepositVerifier } from "./DepositVerifier";
