/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as basic from "./basic";
export type { basic };
import type * as deposit from "./deposit";
export type { deposit };
