/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deposit from "./deposit";
export type { deposit };
import type * as spend11 from "./spend_11";
export type { spend11 };
import type * as spend12 from "./spend_12";
export type { spend12 };
import type * as spend21 from "./spend_21";
export type { spend21 };
import type * as spend22 from "./spend_22";
export type { spend22 };
