/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as deposit from "./deposit";
export * as spend11 from "./spend_11";
export * as spend12 from "./spend_12";
export * as spend21 from "./spend_21";
export * as spend22 from "./spend_22";
