[package]
name = "basic"
type = "bin"
authors = ["Dzmitry Lahunouski <killroy192@gmail.com>"]
compiler_version = ">=0.35.0"

[dependencies]
poseidon = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }